//
//  Constants_Images.h
//  Rover
//
//  Created by Sean Fitzgerald on 3/9/14.
//  Copyright (c) 2014 Sean T Fitzgerald. All rights reserved.
//

#ifndef Rover_Constants_Images_h
#define Rover_Constants_Images_h

#define RV_IMAGES_LAUNCH_SCREEN_BACKGROUND (@"backgroundlaunchScreen@2x")
#define RV_IMAGES_LAUNCH_SCREEN_MONTAGE_PLUTO (@[@"launchSequence0@2x",@"launchSequence1@2x",@"launchSequence2@2x",@"launchSequence3@2x",@"launchSequence4@2x",@"launchSequence5Pluto@2x",@"launchSequence6Pluto@2x",@"launchSequence7Pluto@2x",@"launchSequence8Pluto@2x",@"launchSequence9Pluto@2x",@"launchSequence10Pluto@2x",@"launchSequence11Pluto@2x",@"launchSequence12Pluto@2x",@"launchSequence13Pluto@2x",@"launchSequence14Pluto@2x"]) //put the names with the format @"NAME", separated by commas
#define RV_IMAGES_LAUNCH_SCREEN_MONTAGE_TITAN (@[@"launchSequence0@2x",@"launchSequence1@2x",@"launchSequence2@2x",@"launchSequence3@2x",@"launchSequence4@2x",@"launchSequence5Titan@2x",@"launchSequence6Titan@2x",@"launchSequence7Titan@2x",@"launchSequence8Titan@2x",@"launchSequence9Titan@2x",@"launchSequence10Titan@2x",@"launchSequence11Titan@2x",@"launchSequence12Titan@2x",@"launchSequence13Titan@2x",@"launchSequence14Titan@2x"]) //put the names with the format @"NAME", separated by commas
#define RV_IMAGES_LAUNCH_SCREEN_MONTAGE_MARS (@[@"launchSequence0@2x",@"launchSequence1@2x",@"launchSequence2@2x",@"launchSequence3@2x",@"launchSequence4@2x",@"launchSequence5Mars@2x",@"launchSequence6Mars@2x",@"launchSequence7Mars@2x",@"launchSequence8Mars@2x",@"launchSequence9Mars@2x",@"launchSequence10Mars@2x",@"launchSequence11Mars@2x",@"launchSequence12Mars@2x",@"launchSequence13Mars@2x",@"launchSequence14Mars@2x"]) //put the names with the format @"NAME", separated by commas
#define RV_IMAGES_LAUNCH_SCREEN_MONTAGE_MOON (@[@"launchSequence0@2x",@"launchSequence1@2x",@"launchSequence2@2x",@"launchSequence3@2x",@"launchSequence4@2x",@"launchSequence5Moon@2x",@"launchSequence6Moon@2x",@"launchSequence7Moon@2x",@"launchSequence8Moon@2x",@"launchSequence9Moon@2x",@"launchSequence10Moon@2x",@"launchSequence11Moon@2x",@"launchSequence12Moon@2x",@"launchSequence13Moon@2x",@"launchSequence14Moon@2x"]) //put the names with the format @"NAME", separated by commas

#define RV_IMAGES_TITLE_SCREEN_BACKGROUND (@"backgroundTitleScreen@2x")
#define RV_IMAGES_TITLE_SCREEN_START_BUTTON_UP (@"startButton@2x")
#define RV_IMAGES_TITLE_SCREEN_START_BUTTON_DOWN (@"startButtonDown@2x")

#define RV_IMAGES_PLANET_SELECT_SCREEN_MOON_GLOW (@"moonGlow@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_TITAN_GLOW (@"titanGlow@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_MARS_GLOW (@"marsGlow@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLUTO_GLOW (@"plutoGlow@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_EXIT_BUTTON (@"exitButton@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_EXIT_BUTTON_DOWN (@"exitButtonDown@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_LETS_GO_BUTTON (@"buildRoverButton@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_LETS_GO_BUTTON_DOWN (@"buildRoverButtonDown@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_LETS_GO_BUTTON_GLOW (@"checkMark@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLANET_INFORMATION_MARS (@"marsDescription@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLANET_INFORMATION_MOON (@"moonDescription@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLANET_INFORMATION_PLUTO (@"plutoDescription@2x")
#define RV_IMAGES_PLANET_SELECT_SCREEN_PLANET_INFORMATION_TITAN (@"titanDescription@2x")

#define RV_IMAGES_PLANET_SELECT_SCREEN_BACKGROUND (@"backgroundPlanetSelectScreen@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_BACKGROUND (@"backgroundRoverBuildScreen@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_SCROLLBAR (@"scrollBarNubs@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TOOL_TYPE_BUTTONS_ANALYSIS_UP (@"toolButtonsAnalysisButtonDown_replacement2@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TOOL_TYPE_BUTTONS_TRANSPORTATION_UP (@"toolButtonsLocomotionButtonDown_replacement2@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TOOL_TYPE_BUTTONS_COMMUNICATION_UP (@"toolButtonsCommunicationButtonDown_replacement2@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_COMMUNICATION_TOOLS_SHADOWS (@"CommunicationToolShadows@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_COMMUNICATION_TOOLS_PANCAM (@"panCam@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_COMMUNICATION_TOOLS_LGANTENNA (@"lowGainAntenna@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_COMMUNICATION_TOOLS_HGANTENNA (@"highGainAntenna@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TRANSPORTATION_TOOLS_SHADOWS (@"LocomotionToolShadows@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TRANSPORTATION_TOOLS_WHEELS (@"wheels@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TRANSPORTATION_TOOLS_TREADS (@"treads@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_TRANSPORTATION_TOOLS_HOVERCRAFT (@"hovercraft@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_SHADOWS (@"AnalysisToolShadows@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_MICROSCOPE (@"microscope@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_ROCK_GRINDER (@"rockGrinder@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_SPECTROMETER (@"spectrometer@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_CHEMCAM (@"chemCam@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_WEATHER_STATION (@"weatherStation@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_ANALYSIS_TOOLS_LASER_DRILL (@"laserDrill@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_LAUNCH_ROVER_BUTTON (@"launchRoverButton@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_LAUNCH_ROVER_BUTTON_DOWN (@"launchRoverButtonDown@2x")
#define RV_IMAGES_ROVER_BUILD_SCREEN_LAUNCH_ROVER_BUTTON_GLOW (@"checkMark@2x")

#define RV_IMAGES_GAME_PLAY_SCREEN_BACKGROUND (@"backgroundGamePlayScreen@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MAP_PLUTO (@"pluto@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MAP_MARS (@"mars@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MAP_TITAN (@"titan@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MAP_MOON (@"moon@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMMMAND_LINEUP_BACKGROUND (@"commandLineupBackground@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_UNDO_BUTTON (@"undoButton@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_UNDO_BUTTON_DOWN (@"undoButtonDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_SEND_COMMAND_BUTTON (@"sendCommandButton@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_SEND_COMMAND_BUTTON_DOWN (@"sendCommandButtonDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MOVE_FORWARD_BUTTON (@"moveForwardButton@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MOVE_FORWARD_BUTTON_DOWN (@"moveForwardButtonDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_ANALYZE_BUTTON (@"analyzeButton@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_ANALYZE_BUTTON_DOWN (@"analyzeButtonDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROBOT_ARM_BUTTON (@"robotArmButton@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROBOT_ARM_BUTTON_DOWN (@"robotArmButtonDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_LEFT_BUTTON (@"turnLeftButton@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_LEFT_BUTTON_DOWN (@"turnLeftButtonDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_AROUND_BUTTON (@"turnAroundButton@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_AROUND_BUTTON_DOWN (@"turnAroundButtonDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_RIGHT_BUTTON (@"turnRightButton@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_RIGHT_BUTTON_DOWN (@"turnRightButtonDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_4 (@"battery4@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_3 (@"battery3@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_2 (@"battery2@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_1 (@"battery1@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_BATTERY_IMAGE_1_RED (@"battery1Red@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_TEXT_1 (@"compassRoseObjective1@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_TEXT_2 (@"compassRoseObjective2@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_TEXT_3 (@"compassRoseObjective3@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_OUTER (@"compassRoseLargeCircle@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_INNER (@"compassRoseSmallCircle@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_COMPASS_ROSE_ARROW (@"compassRoseArrow@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROCK_MARS (@"BreakableRockMars@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROCK_TITAN (@"BreakableRockTitan@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROCK_PLUTO (@"BreakableRockPluto@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_ROCK_MOON (@"BreakableRockMoon@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_OBJECTIVE (@"objective@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_YES (@"tutorialYes@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_YES_DOWN (@"tutorialYesDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_NO (@"tutorialNo@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_NO_DOWN (@"tutorialNoDown@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_1 (@"tutorial1@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_2 (@"tutorial2@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_3 (@"tutorial3@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_4 (@"tutorial4@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_5 (@"tutorial5@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_6 (@"tutorial6@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_7 (@"tutorial7@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_8 (@"tutorial8@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TUTORIAL_9 (@"tutorial9@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TRASMITTING_SIGNAL (@"transmittingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_RECEIVING_SIGNAL (@"receivingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_PLUTO_TRASMITTING_SIGNAL (@"plutoTransmittingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_PLUTO_RECEIVING_SIGNAL (@"plutoReceivingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MARS_TRASMITTING_SIGNAL (@"marsTransmittingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MARS_RECEIVING_SIGNAL (@"marsReceivingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MOON_TRASMITTING_SIGNAL (@"moonTransmittingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_MOON_RECEIVING_SIGNAL (@"mooonReceivingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TITAN_TRASMITTING_SIGNAL (@"titanTransmittingSignal@2x")
#define RV_IMAGES_GAME_PLAY_SCREEN_TITAN_RECEIVING_SIGNAL (@"titanReceivingSignal@2x")

#define RV_MAP_PATH_INIT_IMAGE_NAME (@"mapPathInit@2x")
#define RV_MAP_PATH_STRAIGHT_IMAGE_NAME (@"mapPathStraight@2x")
#define RV_MAP_PATH_STRAIGHT_END_IMAGE_NAME (@"mapPathStraightEnd@2x")
#define RV_MAP_PATH_CURVED_IMAGE_NAME (@"mapPathCurved@2x")
#define RV_MAP_PATH_CURVED_END_IMAGE_NAME (@"mapPathCurvedEnd@2x")
#define RV_MAP_PATH_AROUND_IMAGE_NAME (@"mapPathAround@2x")
#define RV_MAP_PATH_AROUND_END_IMAGE_NAME (@"mapPathAroundEnd@2x")
#define RV_MAP_PATH_TOOL_IMAGE_NAME (@"mapPathRoverTool@2x")
#define RV_MAP_PATH_ANALYZE_IMAGE_NAME (@"mapPathAnalyze@2x")

#define RV_IMAGES_VICTORY_SCREEN_CONTINUE_BUTTON_BACKGROUND (@"continueButton_background@2x")
#define RV_IMAGES_VICTORY_SCREEN_CONTINUE_BUTTON (@"continueButton_noback@2x")
#define RV_IMAGES_VICTORY_SCREEN_CONTINUE_BUTTON_DOWN (@"continueButtonDown_noback@2x")
#define RV_IMAGES_VICTORY_SCREEN_INDIA_FAILURE (@"fIndia@2x")
#define RV_IMAGES_VICTORY_SCREEN_INDIA_SUCCESS (@"sIndia@2x")
#define RV_IMAGES_VICTORY_SCREEN_JACOB_FAILURE (@"fJacob@2x")
#define RV_IMAGES_VICTORY_SCREEN_JACOB_SUCCESS (@"sJacob@2x")
#define RV_IMAGES_VICTORY_SCREEN_MOON_THERMOMETER_3_MONTAGE_NAMES (@[@"moonThermometer11@2x", @"moonThermometer0@2x", @"moonThermometer9@2x", @"moonThermometer8@2x", @"moonThermometer7@2x", @"moonThermometer6@2x", @"moonThermometer5@2x", @"moonThermometer4@2x", @"moonThermometer3@2x", @"moonThermometer2@2x", @"moonThermometer1@2x", @"moonThermometer0@2x"])
#define RV_IMAGES_VICTORY_SCREEN_MOON_THERMOMETER_2_MONTAGE_NAMES (@[@"moonThermometer11@2x", @"moonThermometer0@2x", @"moonThermometer9@2x", @"moonThermometer8@2x", @"moonThermometer7@2x", @"moonThermometer6@2x", @"moonThermometer5@2x", @"moonThermometer4@2x", @"moonThermometer3@2x", @"moonThermometer2@2x", @"moonThermometer1@2x"])
#define RV_IMAGES_VICTORY_SCREEN_MOON_THERMOMETER_1_MONTAGE_NAMES (@[@"moonThermometer11@2x", @"moonThermometer0@2x", @"moonThermometer9@2x", @"moonThermometer8@2x", @"moonThermometer7@2x", @"moonThermometer6@2x", @"moonThermometer5@2x", @"moonThermometer4@2x", @"moonThermometer3@2x", @"moonThermometer2@2x"])
#define RV_IMAGES_VICTORY_SCREEN_PLUTO_OBJECTIVE_1 (@"objective1Pluto@2x")
#define RV_IMAGES_VICTORY_SCREEN_PLUTO_OBJECTIVE_2 (@"objective2Pluto@2x")
#define RV_IMAGES_VICTORY_SCREEN_PLUTO_OBJECTIVE_3 (@"objective3Pluto@2x")
#define RV_IMAGES_VICTORY_SCREEN_MARS_OBJECTIVE_1 (@"objectiveMars1@2x")
#define RV_IMAGES_VICTORY_SCREEN_MARS_OBJECTIVE_2 (@"objectiveMars2@2x")
#define RV_IMAGES_VICTORY_SCREEN_MARS_OBJECTIVE_3 (@"objectiveMars3@2x")
#define RV_IMAGES_VICTORY_SCREEN_MARS_OBJECTIVE_4 (@"objectiveMars4@2x")
#define RV_IMAGES_VICTORY_SCREEN_MOON_OBJECTIVE (@"objectiveMoon@2x")
#define RV_IMAGES_VICTORY_SCREEN_TITAN_OBJECTIVE_1 (@"objectiveTitan1@2x")
#define RV_IMAGES_VICTORY_SCREEN_TITAN_OBJECTIVE_2 (@"objectiveTitan2@2x")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL (@"objectiveFail@2x")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL_MARS (@"backgroundFailureMars@2x")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL_TITAN (@"backgroundFailureTitan@2x")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL_PLUTO (@"backgroundFailurePluto@2x")
#define RV_IMAGES_VICTORY_SCREEN_OBJECTIVE_FAIL_MOON (@"backgroundFailureMoon@2x")
#define RV_IMAGES_VICTORY_SCREEN_PLUTO_FLASH (@"plutoFlash@2x")
#define RV_IMAGES_VICTORY_SCREEN_TRY_AGAIN_BUTTON (@"tryAgainButton@2x")
#define RV_IMAGES_VICTORY_SCREEN_TRY_AGAIN_BUTTON_DOWN (@"tryAgainButtonDown@2x")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_BACKGROUND (@"twoButtonBackground@2x")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_CONTINUE (@"twoButtonContinue@2x")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_CONTINUE_DOWN (@"twoButtonContinueDown@2x")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_END (@"twoButtonEnd@2x")
#define RV_IMAGES_VICTORY_SCREEN_TWO_BUTTON_END_DOWN (@"twoButtonEndDown@2x")

#endif
